2021-01-18 22:39:05,427 INFO    MainThread:9446 [internal.py:wandb_internal():62] W&B internal server running at pid: 9446
2021-01-18 22:39:05,431 DEBUG   HandlerThread:9446 [handler.py:handle_request():54] handle_request: login
2021-01-18 22:39:05,432 DEBUG   SenderThread:9446 [sender.py:send():91] send: request
2021-01-18 22:39:05,432 DEBUG   SenderThread:9446 [sender.py:send_request():100] send_request: login
2021-01-18 22:39:05,441 DEBUG   SenderThread:9446 [connectionpool.py:_new_conn():943] Starting new HTTPS connection (1): api.wandb.ai:443
2021-01-18 22:39:14,313 DEBUG   SenderThread:9446 [connectionpool.py:_make_request():442] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2021-01-18 22:39:14,661 INFO    SenderThread:9446 [sender.py:send_request_login():147] Login server info: {'cliVersionInfo': {'min_cli_version': '0.8.20', 'max_cli_version': '0.10.13'}}
2021-01-18 22:40:28,236 WARNING MainThread:9446 [internal.py:wandb_internal():116] Internal process interrupt: 1
2021-01-18 22:40:28,384 WARNING MainThread:9446 [internal.py:wandb_internal():116] Internal process interrupt: 2
2021-01-18 22:40:28,385 ERROR   MainThread:9446 [internal.py:wandb_internal():119] Internal process interrupted.
2021-01-18 22:40:28,530 INFO    HandlerThread:9446 [handler.py:finish():267] shutting down handler
2021-01-18 22:40:28,676 INFO    SenderThread:9446 [sender.py:finish():548] shutting down sender
2021-01-18 22:40:28,677 INFO    MainThread:9446 [internal.py:handle_exit():137] Internal process exited
